# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{candy}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen Eley"]
  s.date = %q{2010-05-03}
  s.description = %q{Candy provides simple, transparent object persistence for the MongoDB database.  Classes that 
include Candy modules save all properties to Mongo automatically, can be recursively embedded,
and can retrieve records with chainable open-ended class methods, eliminating the need for 
method calls like 'save' and 'find.'
}
  s.email = %q{sfeley@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.markdown",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY.markdown",
     "LICENSE.markdown",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "candy.gemspec",
     "lib/candy.rb",
     "lib/candy/array.rb",
     "lib/candy/collection.rb",
     "lib/candy/crunch.rb",
     "lib/candy/embeddable.rb",
     "lib/candy/exceptions.rb",
     "lib/candy/factory.rb",
     "lib/candy/hash.rb",
     "lib/candy/piece.rb",
     "lib/candy/qualified_const_get.rb",
     "lib/candy/wrapper.rb",
     "spec/candy/array_spec.rb",
     "spec/candy/collection_spec.rb",
     "spec/candy/crunch_spec.rb",
     "spec/candy/hash_spec.rb",
     "spec/candy/piece_spec.rb",
     "spec/candy/wrapper_spec.rb",
     "spec/candy_spec.rb",
     "spec/spec.opts",
     "spec/spec.watchr",
     "spec/spec_helper.rb",
     "spec/support/kitkat_fixture.rb",
     "spec/support/zagnuts_fixture.rb"
  ]
  s.homepage = %q{http://github.com/SFEley/candy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Transparent persistence for MongoDB}
  s.test_files = [
    "spec/candy/array_spec.rb",
     "spec/candy/collection_spec.rb",
     "spec/candy/crunch_spec.rb",
     "spec/candy/hash_spec.rb",
     "spec/candy/piece_spec.rb",
     "spec/candy/wrapper_spec.rb",
     "spec/candy_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/kitkat_fixture.rb",
     "spec/support/zagnuts_fixture.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bson>, [">= 0.20.1"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 0.20.1"])
      s.add_runtime_dependency(%q<mongo>, [">= 0.20.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
    else
      s.add_dependency(%q<bson>, [">= 0.20.1"])
      s.add_dependency(%q<bson_ext>, [">= 0.20.1"])
      s.add_dependency(%q<mongo>, [">= 0.20.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<bson>, [">= 0.20.1"])
    s.add_dependency(%q<bson_ext>, [">= 0.20.1"])
    s.add_dependency(%q<mongo>, [">= 0.20.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
  end
end

